name: webscraper
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.8
  - pip>=22.0
  - beautifulsoup4>=4.12.0
  - requests>=2.31.0
  - selenium>=4.0.0
  - toml>=0.10.2
  # Testing dependencies
  - pytest>=7.0.0
  - pytest-mock>=3.10.0
  - pytest-cov>=4.0.0
  - responses>=0.23.0  # For mocking HTTP requests
  - pip:
    - hatchling  # For building the package 